export const quizProperties = {
    questions: [
    "As I reflect on my daily routine, my faith and	my relationship with God is my highest priority.",
    "I accept the Apostles' Creed as a foundational statement for what I believe and understand it in relation to life today.",
    "Daily, I am actively answering God’s call to serve	the poor and suffering.",
    "While worshipping God, am I very rarely distracted?",
    "I am reading scripture daily. Each day, I am	praying without ceasing.",
    "The people who have influence in my life are	from a diverse group of races, religions, and	genders.",
    "Each day, I take time to stop and praise God for His creative hand in my world.",
    "As I realize more and more how much Jesus loves me, every day I find myself loving people	more.",
    "Everyday in my life, I listen and obey in whatever direction the Holy Spirit leads me.",
    "I pray every day for the Holy Spirit to lead	and direct me.",
    "I do not let other activities (TV, internet,	recreation, work) get in the way of my daily relationship with Jesus.",
    "Without exception, when I hear the daily news from around the world, I am moved to prayer.",
    "“Daily intimacy” is a phrase I would use to describe my relationship with the Lord.",
    "Those close to me would describe me as a	passionate follower of Jesus.",
    "Many times in my day I pray believing; the Holy Spirit works through my life and the lives of others, calling and guiding us to do God’s work in the world.",
    "I realize that worship is not about pleasing me but glorifying God.",
    "I have been very active in my local church for	years.",
    "I regularly invite others to come to church with me.",
    "I read the Bible daily so I can know God more and more.",
    "Each day, I specifically set time aside for solitude	and to listen to God.",
    "I know my talents and spiritual gifts and am	actively serving Christ by using those gifts.",
    "Without exception I pray prior to our worship,	asking for God’s presence and power to come	among us.",
    "When facing daily decisions, I submissively seek God’s will through the Bible, prayer, and	the wisdom of mature Christians I trust.",
    "Daily, I give away my time to serve and help others in my community.",
    "Each day I am driven and hungry to know God 	more deeply.",
    "I believe salvation is graciously offered to me 	as a gift through Jesus’ death and resurrection, not something I earn by anything I do, and I trust that Jesus is my Savior and	Lord of my life.",
    "Each day, because everything ultimately belongs to God, I am generous with all the	resources (time, 	talent and treasure) I have.",
    "Without exception, I prepare my heart and mind before participating in worship.",
    "I am never defensive; as those of my church community hold me accountable for the way I live as a follower of Jesus.",
    "I make a spiritual impact in my home, school, and/or work through my consistent daily 	example that invites others to ask why I live that way.",
    "Without exception those who know me, would	say I live a life displaying God is not a vague	concept; God is a living reality for me.",
    "As a means of growing in Christ, each day I prayerfully practice various spiritual 	disciplines for example, meditation, praying,	fasting, fellowship, journaling etc.",
    "Several times a week, I actively participate in a ministry that serves our community.",
    "I can quickly find any scripture a teacher or pastor invites us to study.",
    "My family would tell you without exception	that my relationship with Jesus is the most	important relationship in my life.",
    "My life choices always reflect my commitment	to serve God and others is life-long: I will never “retire” from it.",
    "With every waking moment of my life I believe the God of the Bible is the one true God —	Father, Son	and Holy Spirit.",
    "Without exception my choices in life reflect	that I believe a Christian should live a sacrificial life that is not driven by pursuit of material things.",
    "Frequently throughout my weekly routine, I	intentionally spend time with people who do not	know Jesus.",
    "Every day, I confess my sins, repent of wrong thoughts, words, and deeds and offer my life to God for obedient service.",
    "My giving (time, talent and treasure) to the	church shows that following Jesus is the top priority in my life.",
    "Several times each week, I find I am	comfortable talking to others about Jesus’ love for me and my trust in him.",
    "I daily worship God when I am alone and I weekly worship God with my church family.",
    "I say enthusiastically, I understand the	Christian faith well enough to teach it to 	others.",
    "Without exception, people in the church would call me a spiritual leader.",
    "I recognize that in the sacraments Jesus is encountering us in a real but mysterious way.",
    "Almost daily I am seeing the fruit of the Spirit (love, joy, peace, patience, kindness,	generosity, faithfulness, gentleness, and self-control) growing in me.",
    "I actively seek out opportunities to share my faith story with other people."
  ]
};
